#!/usr/bin/env php
<?php

if($argv[1]) {
    if(is_file($argv[1])){
        (new DK($argv[1],$argv[2] ?? null));
    }else {
        echo("File not found : $argv[1]");
    }
}
else {
    echo("\nUsage :\n");
    echo("dk translate [file] [destination]");
}
?>